model_params:
  image_height: 64
  image_width: 64
  im_channels: 12
  emb_dim: 768
  patch_emb_drop: 0.1
  patch_height: 4
  patch_width: 4
  num_heads: 8
  mlp_dim: 2048
  dropout_rate: 0.1
  num_layers: 12

dataset_params:
  file_pattern: '/Users/lzm/Desktop/7980 Capstone/rayan 项目/northamerica_2012-2023/train/*_ongoing_*.tfrecord'
  data_size: 64
  sample_size: 64
  batch_size: 32
  num_in_channels: 12
  clip_and_normalize: True
  clip_and_rescale: False
  random_crop: True
  center_crop: False

train_params:
  task_name: 'training_task'
  ckpt_name: 'model_checkpoint.pth'
  batch_size: 32

num_classes: 1  # same as Bronte code, but not sure 